[package]
name = "iron-post"
version = "0.0.1"

[dependencies]
iron = "0.3.0"
bodyparser = "0.3.0"
mount = "0.1.0"
router = "0.1.1"
hyper = { version = "0.9.8", default-features = false, features = [""] }
